Altinn/altinn-authorization-tmp

.github/workflows/apps-cd.yml, .github/workflows/infra-cd.yml, .github/workflows/infra-ci.yml
Remove AT22-24 Deplyos due to unfinished infrastructure setup
=> Remove AT[22-24] deploys

infra/modules/key_vault/main.tf
=> chore: use each value in kv module for role assignment

infra/deploy/auth/variables.tf, infra/modules/container_app/main.tf, src/apps/Altinn.Authorization.DeployApi/deploy/main.tf, src/apps/Altinn.Authorization.DeployApi/metadata.json, src/apps/Altinn.Authorization.DeployApi/src/Altinn.Authorization.DeployApi/Program.cs
=> chore: rename deploy to bootstrap

src/apps/Altinn.Authorization.DeployApi/src/Altinn.Authorization.DeployApi/Altinn.Authorization.DeployApi.csproj, src/apps/Altinn.Authorization.DeployApi/src/Altinn.Authorization.DeployApi/Program.cs
=> chore: add health endpoints

src/apps/Altinn.Authorization.DeployApi/deploy/main.tf
=> chores: update client_id variables for deployapi

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/epic.md, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/task.md, .github/ISSUE_TEMPLATE/testplan.md
=> add github issues templates

.github/workflows/_deploy-app.yml, .github/workflows/infra-cd.yml
=> chores: add at22 workflows

.github/workflows/_ci-infra-template.yml, .github/workflows/cd-infra.yml, .github/workflows/ci-infra.yml
=> chores: update infra templates

.github/workflows/_ci-infra-template.yml, .github/workflows/_deploy-app-terraform.yml, .github/workflows/ci-infra.yml, infra/deploy/altinn-register/main.tf, infra/modules/container_app/main.tf, infra/modules/container_app_api/main.tf, infra/modules/service_bus/main.tf
=> chores: add at22

infra/modules/postgres_server/main.tf
Lower tier for pgsql srv in not prod like environements in order to downscale costs
=> chores: tune pgsqlsrv

src/apps/Altinn.AccessManagement/Dockerfile
=> chores:update-docker for access management

.github/workflows/pr-apps.yml, .github/workflows/pr-pkgs.yml
=> add ci on prs

src/apps/Altinn.AccessManagement/test/Bruno/Altinn.AccessManagement/Automatic Test Collection/RightsInternal/accesslist-resource/AccessListDelegation_Dagl_OrgPartialAccessRead.bru
Final fix for AccessList delegationcheck and delegation
- #172
=> Fixed testdata AT

src/Directory.Packages.props
v2.6.0 has issues with open api spec generation
=> Rollback Altinn.Urn.Swashbuckle from 2.6.0 to 2.5.1

infra/deploy/hub/storage.tf, infra/deploy/hub/variables.tf
=> Formatted TF hub

infra/deploy/hub/prod.tfvars, infra/deploy/hub/variables.tf
=> Add prod.tfvars

infra/deploy/hub/firewall.tf
=> remove identity for firewall policy

infra/deploy/hub/app_configuration.tf, infra/deploy/hub/firewall.tf, infra/deploy/hub/key_vault.tf, infra/deploy/hub/prod.tfvars, infra/deploy/hub/variables.tf, infra/deploy/hub/vpn.tf
* Add maintainers as param to make plan deterministic
=> Chores: Add maintainers

infra/deploy/hub/app_configuration.tf, infra/deploy/hub/firewall.tf, infra/deploy/spoke/.terraform.lock.hcl, infra/deploy/spoke/at21.tfvars, infra/deploy/spoke/main.tf, infra/deploy/spoke/variables.tf, infra/modules/postgres/main.tf, infra/modules/postgres/variables.tf
=> Rename app_configuration_owner and add spoke network

.github/workflows/pr-apps.yml
=> Initial augmentation of pr-apps.yml

infra/deploy/spoke/key_vault.tf, infra/deploy/spoke/main.tf
=> chores/identity: Update Spoke Managed Identity

infra/deploy/altinn-register/main.tf, infra/deploy/hub/firewall.tf, infra/deploy/hub/key_vault.tf, infra/deploy/hub/main.tf, infra/deploy/hub/storage.tf, infra/deploy/hub/vpn.tf, infra/deploy/spoke/key_vault.tf, infra/deploy/spoke/main.tf, infra/modules/postgres/main.tf, infra/modules/postgres/outputs.tf
=> chores/locks: Add TF prevent_destroy and ARM lock

infra/deploy/spoke/main.tf
=> chores: Add pgsql delegations permission

infra/deploy/altinn-register/main.tf, infra/deploy/hub/main.tf, infra/deploy/spoke/main.tf, infra/modules/postgres/main.tf, infra/modules/postgres/variables.tf
=> chores: add pgsql subnet delegations

infra/deploy/altinn-register/main.tf
=> chore: change scope for ARM lock register DB

infra/deploy/hub/main.tf, infra/modules/postgres/main.tf
=> chores: ignore change to zone for pgsqlsrv

src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/RightsInternal/SystemUser/o2s delegate org2systemuser.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/RightsInternal/SystemUser/o2s sending org revokes delegation to systemuser.bru
=> Bruno test revoke System User

.github/workflows/sonarcloud-apps.yml
Added a new Github Actions workflow that is basically a clone of PR: Apps, but with no triggers so that it can only be manually executed from Github, and without the if statements that stops a manual scan outside of PRs.
- #152
=> Added Github Actions workflow for manual Sonarcloud analysis for apps.

infra/deploy/hub/app_configuration.tf, infra/deploy/hub/key_vault.tf, infra/deploy/hub/main.tf, infra/deploy/hub/prod.tfvars, infra/deploy/hub/variables.tf, infra/deploy/hub/vpn.tf
* Updated RBAC settings for hub resources
=> chores/add: app conf readers

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Integration/Clients/AuthenticationClient.cs
=> add query parameter useoldformatforapp to fetch rights for a system

infra/deploy/hub/prod.tfvars
=> chores: update VPN config

src/libs/Altinn.Authorization.Host/src/Altinn.Authorization.Host/AppSettingsOptions.cs
=> chores: set default empty list for appsettings

infra/deploy/altinn-register/main.tf
=> chores: remove register from deploy

infra/modules/appsettings/main.tf, infra/modules/appsettings/variables.tf, infra/modules/rbac/main.tf, infra/modules/rbac/variables.tf, src/apps/Altinn.AccessManagement/infra/main.tf
=> chores: add providers to modules

.github/workflows/_cd-infra-template.yml, .github/workflows/_ci-infra-template.yml, .github/workflows/_deploy-app-terraform.yml, .github/workflows/ci-infra.yml
=> chores: add TF version to gh action templates

src/apps/Altinn.Register/infra/main.tf
=> chores: add register infra

infra/modules/postgres/variables.tf, src/apps/Altinn.Register/infra/main.tf
* Set register DB to 16
* Fix TF reference in register
=> chores: fix resource reference in register TF

infra/deploy/hub/app_configuration.tf, infra/deploy/spoke/main.tf, infra/modules/appsettings/main.tf, infra/modules/appsettings/variables.tf, infra/modules/rbac/main.tf, infra/modules/rbac/variables.tf, src/apps/Altinn.AccessManagement/infra/main.tf, src/apps/Altinn.Register/infra/main.tf
=> chores: add register infrastructure

infra/modules/appsettings/main.tf
=> chores: update feature flag for access mgmt

infra/deploy/spoke/prod.tfvars, src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/appsettings.json
=> chores: add tfvars environment name

src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/AppsInstanceDelegation/DelegationCheck/InstDelg_DelgChk_PlatformAccessToken_OkEmpty.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Testdata/instance-delegation/tt02.json
=> AccMgmt | Fix for failing bruno tests in TT02

infra/modules/appsettings/main.tf, src/apps/Altinn.Register/infra/main.tf
* Fix Key Value Reference in Appsettings module
=> chores: fix var reference in appsettings module

.github/workflows/_deploy-app-terraform.yml, src/apps/Altinn.Register/infra/main.tf
=> chores: adjust bootstrap cmd

.github/workflows/_cd-infra-template.yml, .github/workflows/_ci-infra-template.yml, .github/workflows/_deploy-app-terraform.yml, .github/workflows/_deploy-app.yml, .github/workflows/cd-apps.yml, infra/deploy/spoke/main.tf, infra/modules/appsettings/main.tf, infra/modules/key_vault/main.tf, src/apps/Altinn.Register/infra/at22.tfvars, src/apps/Altinn.Register/infra/at23.tfvars, src/apps/Altinn.Register/infra/at24.tfvars, src/apps/Altinn.Register/infra/main.tf, src/apps/Altinn.Register/infra/prod.tfvars, src/apps/Altinn.Register/infra/tt02.tfvars, src/apps/Altinn.Register/infra/variables.tf, src/apps/Altinn.Register/infra/yt01.tfvars, src/tools/Altinn.Authorization.Cli/src/Altinn.Authorization.Cli/Database/BootstapCommand.cs
* Make sure that DB bootstrap runs under deployment for register
* Update DNS in gh action
* Make sure that deployment app has permission to manage register kv
=> chores: add DB bootstrap as part of deployment 

infra/deploy/spoke/storage.tf
=> add lease container

.github/workflows/_deploy-app.yml, infra/deploy/spoke/service_bus.tf, src/apps/Altinn.Register/infra/main.tf
=> chores: rename service bus pep and update deploy pipeline for apps 

.github/workflows/_deploy-app.yml
=> chores: fix dependency in app deployment

src/apps/Altinn.Register/infra/main.tf
=> chores: add reading of conf.json file in tf

infra/modules/appsettings/main.tf, infra/modules/appsettings/variables.tf, src/apps/Altinn.AccessManagement/infra/main.tf, src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/AccessManagementFeatureFlags.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/AccessManagementHost.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/Controllers/DelegationRequestsController.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/HostedServices/RegisterHostedService.cs, src/apps/Altinn.Register/infra/main.tf, src/libs/Altinn.Authorization.Integration/src/Altinn.Authorization.Integration.Platform/AccessManagement/AltinnAccessManagementClient.cs, src/libs/Altinn.Authorization.Integration/src/Altinn.Authorization.Integration.Platform/AccessManagement/AltinnAccessManagementOptions.cs, src/libs/Altinn.Authorization.Integration/src/Altinn.Authorization.Integration.Platform/Altinn.Authorization.Integration.Platform.csproj, src/libs/Altinn.Authorization.Integration/src/Altinn.Authorization.Integration.Platform/PaginatorStream.cs, src/libs/Altinn.Authorization.Integration/src/Altinn.Authorization.Integration.Platform/PlatformResponse.cs, src/libs/Altinn.Authorization.Integration/src/Altinn.Authorization.Integration.Platform/Register/PartiesStreamEndpoint.cs, src/libs/Altinn.Authorization.Integration/src/Altinn.Authorization.Integration.Platform/Register/RegisterClient.cs, src/libs/Altinn.Authorization.Integration/src/Altinn.Authorization.Integration.Platform/Register/RoleStreamEndpoint.cs, src/libs/Altinn.Authorization.Integration/src/Altinn.Authorization.Integration.Platform/RequestComposer.cs, src/libs/Altinn.Authorization.Integration/src/Altinn.Authorization.Integration.Platform/ResourceRegister/ResourceRegisterClient.cs, src/libs/Altinn.Authorization.Integration/src/Altinn.Authorization.Integration.Platform/ResourceRegister/ResourceUpdatedEndpoint.cs, src/libs/Altinn.Authorization.Integration/src/Altinn.Authorization.Integration.Platform/ResponseComposer.cs
=> chores: update platform integration

infra/deploy/spoke/storage.tf
=> chores: fix account replication tier

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/appsettings.Startup.json
=> chores: trigger redeploy

infra/deploy/hub/telemetry.tf, src/apps/Altinn.Register/infra/main.tf
=> chores: add telemetry to hub

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/AccessManagementHost.cs
=> chores: reorder database init after appconfig init

infra/deploy/hub/prod.tfvars, src/apps/Altinn.AccessManagement/infra/variables.tf
=> chores: add jk as accessmgmt admin

infra/modules/postgres/main.tf
=> chores: add TF db delete lock for databases

infra/deploy/hub/prod.tfvars, infra/modules/postgres/main.tf
=> add vpn access for havard

infra/deploy/hub/prod.tfvars
=> chores: add cert for aleksh

src/apps/Altinn.Register/infra/main.tf
=> chores: update appsettings for register

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Core/Constants/AuthzConstants.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/AccessManagementHost.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/Controllers/SystemUserClientDelegationController.cs, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Manual Test Collection/SystemUserClientDelegation/DEL_SystemUser_ClientDelegation.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Manual Test Collection/SystemUserClientDelegation/GET_SystemUser_ClientDelegations.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Manual Test Collection/SystemUserClientDelegation/POST_SystemUser_ClientDelegation.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/TestToolsTokenGenerator.js, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Testdata/sharedtestdata.json
Example controller shell for internal endpoint for system user client delegation
Including authorization:
- portal enduser scope
- authenticated user has ClientAdministration access for Party
Endpoints
- POST ClientDelegation
- GET ClientDelegation
- DELET ClientDelegation
=> Example controller shell for internal endpoint for system user client delegation

.justfile, src/tools/Altinn.Authorization.Cli/src/Altinn.Authorization.Cli/Database/BootstapCommand.cs, src/tools/Altinn.Authorization.Cli/src/Altinn.Authorization.Cli/Database/CredentialsCommand.cs
=> chores: fix line wrap for CLI db creds

.github/workflows/cd-pkgs.yml, src/pkgs/README.md, src/pkgs/release-please-config.json
=> chore: add release please

.github/workflows/cd-pkgs.yml, src/pkgs/release-please-manifest.json
=> chores: add release please manifest

src/pkgs/Altinn.Authorization.PEP/README.md
=> release(main):src/pkgs/Altinn.Authorization.PEP 4.1.4

src/apps/Altinn.Register/conf.json
=> chore: add yuniql schema to register

src/apps/Altinn.AccessManagement/infra/at22.tfvars, src/apps/Altinn.AccessManagement/infra/at23.tfvars, src/apps/Altinn.AccessManagement/infra/at24.tfvars, src/apps/Altinn.AccessManagement/infra/main.tf, src/apps/Altinn.AccessManagement/infra/prod.tfvars, src/apps/Altinn.AccessManagement/infra/tt02.tfvars, src/apps/Altinn.AccessManagement/infra/variables.tf, src/apps/Altinn.AccessManagement/infra/yt01.tfvars, src/apps/Altinn.Register/infra/at22.tfvars, src/apps/Altinn.Register/infra/at23.tfvars, src/apps/Altinn.Register/infra/at24.tfvars, src/apps/Altinn.Register/infra/main.tf, src/apps/Altinn.Register/infra/prod.tfvars, src/apps/Altinn.Register/infra/tt02.tfvars, src/apps/Altinn.Register/infra/variables.tf, src/apps/Altinn.Register/infra/yt01.tfvars
=> chores: add max pool size param in TF to pgsqldb bootstrap

infra/deploy/hub/app_configuration.tf
=> chore: add devs as data readers

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Models/RoleLookup.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Data/DbDataMigrationService.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Definitions/RoleLookupDefinition.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Extensions/DbAccessHostExtensions.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Repositories/Contracts/IRoleLookupRepository.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Repositories/RoleLookupRepository.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/Contracts/IRoleService.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/RoleService.cs
Added RoleLookup with Key/Value and a refrence back to Role. 
Unique constraint on RoleId + Key.
Added RoleService for ease of use
=> Added Role Lookup to hold more keys for roles

src/tools/Altinn.Authorization.Cli/src/Altinn.Authorization.Cli/Database/CredentialsCommand.cs
Add option to use interactive to select credential
=> Interactive Credentials

infra/deploy/spoke/prod.tfvars, infra/deploy/spoke/service_bus.tf, infra/deploy/spoke/tt02.tfvars, infra/deploy/spoke/yt01.tfvars, src/apps/Altinn.AccessManagement/infra/prod.tfvars, src/apps/Altinn.AccessManagement/infra/tt02.tfvars, src/apps/Altinn.AccessManagement/infra/yt01.tfvars, src/apps/Altinn.Register/infra/prod.tfvars, src/apps/Altinn.Register/infra/tt02.tfvars, src/apps/Altinn.Register/infra/yt01.tfvars
=> chores: update DB tier and egress firewall for service bus

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Integration/Extensions/IntegrationDependencyInjectionExtensions.cs
rollback change to dependency injection of ResourceRegistryClient
=> rollback change to dependency injection of ResourceRegistryClient

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/Controllers/SystemUserClientDelegationController.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/DelegationService.cs
- When fixing bug in GetClientDelegation changed return model
- Added more details in exceptions
GetClientDelegations - Did not return data, due to input not matching filter. Changed return model from Delegation to Connection. This is better but not the final version of the return model. Also changed return model in Create method to match.
- #410
=> Bugfix - AccessMgmt - ClientDelegation - ReturnModel 

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Metadata/Controllers/PackagesController.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/PackageService.cs
Fixes for package meta api
- #491 
- #490 
- #488
=> Better result from api, fixed export endpoint bug

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Data/DbDataMigrationService.cs
=> Increase version number parameter in relevant NeedMigration checks

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Definitions/DbDefinition.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Definitions/DbDefinitionBuilder.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Helpers/GenericFilterBuilder.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/QueryBuilders/PostgresQueryBuilder.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Services/BasicRepository.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Definitions/ConnectionDefinition.cs
- Added view version
- Fix delete query
- Fix IN query bug
=> Added view version, Fix delete query, fix IN query bug

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/Controllers/SystemUserClientDelegationController.cs
- Delete assignment for agentId
=> New Delete Endpoint for SystemClientDelegation

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Metadata/Controllers/PackagesController.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Definitions/DbDefinitionBuilder.cs
=> Naming fix for apim

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/Controllers/SystemUserClientDelegationController.cs
=> Add check for 0 assignments

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/HostedServices/RegisterHostedService.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Models/StatusRecord.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Definitions/DbConstraintDefinition.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Definitions/DbDefinitionBuilder.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/QueryBuilders/PostgresQueryBuilder.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Services/PostgresIngestService.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Definitions/AssignmentDefinition.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Definitions/EntityLookupDefinition.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Definitions/RoleLookupDefinition.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Definitions/StatusRecordDefinition.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Extensions/DbAccessHostExtensions.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Repositories/Contracts/IStatusRecordRepository.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Repositories/StatusRecordRepository.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/StatusService.cs
Added more fixes for ingest service.
- New RoleSync for pages
- Indexes
=> Chore accessmgmt ingest fixes

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/HostedServices/RegisterHostedService.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Services/PostgresIngestService.cs
- Missing handling of duplikate Adds or Remove of same From/To/Role within the same page/batch
=> Fix for RegisterHostedService.SyncRoles

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/Controllers/SystemUserClientDelegationController.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Models/Connection.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.FFB/Components/Pages/Connection_Details.razor, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.FFB/Components/Pages/Entity_Details.razor, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Definitions/ConnectionDefinition.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/ConnectionService.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/Models/ConnectionDto.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/Models/CreateDelegationResponse.cs
Fjernet unødvendig berikelse av delegation på return av create.
- https://github.com/Altinn/altinn-authentication/issues/1206
=> Removed enrichment of delegation in return

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Utilities/DbConverter.cs
Updated DbConverter in response to bug with private setters
- #543
=> Update DbConverter to handle private properties

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Data/DbDataMigrationService.cs
=> chores: bump provider version in DbMigration

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Internal/appsettings.Development.json, src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Internal/appsettings.json, src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.ServiceOwner/appsettings.Development.json, src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.ServiceOwner/appsettings.json, src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/Altinn.AccessManagement.csproj, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/QueryBuilders/PostgresQueryBuilder.cs
- Update project
- Updated QueryBuilder
- Removed appsettings
=> Update project and QueryBuilder

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Data/DbDataMigrationService.cs
- REPR removed as key role
- REPR removed as MP-admin
- Hovedadmin added relation to eksplisitt-package
- Bump migration versions missing from PR #613
- #616
=> DbDataMigrationService version bumps and keyrole adjustment

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/AssignmentService.cs
=> chores: fix lookup. use code instead of name

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/AssignmentService.cs
=> chore: fix create assignement

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/AssignmentService.cs
=> chores: fix delete assignment - role lookup

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/AccessManagementHost.cs
=> chores: fix init job for access management host

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/AssignmentService.cs
=> chores: fix delete assignment. Use assignment repo instead of role

.github/workflows/tpl-vertical-ci.yml
=> Sonarcloud parameters fix

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/QueryBuilders/PostgresQueryBuilder.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Definitions/ConnectionPackageDefinition.cs
Added filter for RolePackage.EntityVariantId in ConnectionPackage view.
- #622
=> Klientdelegering for forretningsfører

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/DelegationService.cs
Added check for desired type and variant on agent entity.
- #512
=> Bugfix - SystemUser ClientDelegation | Invalid type or variant for agent

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/HostedServices/Services/BaseSyncService.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/HostedServices/Services/RoleSyncService.cs
Bugs in rolesync service. 
- Fixed wrong parameter check urn/code
- Fixed UpdateLease with null
=> Bug | RoleSync 

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Data/DbDataMigrationService.cs
AccMgmt | Fix issue on match columns for Role ingest
=> AccMgmt | Fix issue on match columns for Role ingest

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/AssignmentService.cs
AccMgmt | Fix wrong property used for match on RoleCode
=> AccMgmt | Fix wrong property used for match on RoleCode

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Enduser/Controllers/ConnectionController.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/Controllers/SystemUserClientDelegationController.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Models/Connection.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.FFB/Components/Pages/Entity_Details.razor, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Definitions/ConnectionDefinition.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/ConnectionService.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/Contracts/IConnectionService.cs
AccMgmt | Fix nullable From and To properties in Connections query
#95 
#608
AccMgmt | GET Clients for facilitator org
#384
=> AccMgmt | Fix nullable From and To properties in Connections query

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/Controllers/SystemUserClientDelegationController.cs
AccMgmt | Bugfix GET Clients fetching connecitons in wrong direction (from the fasilitator)
- #384
=> AccMgmt | Bugfix GET Clients fetching connecitons in wrong direction

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Enduser/Controllers/ConnectionController.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Definitions/ConnectionPackageDefinition.cs
Added missing extended query for connectionpackage
- #669
=> Added Extended Query for ConnectionPackage

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Enduser/Controllers/ConnectionController.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/Controllers/SystemUserClientDelegationController.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Definitions/ConnectionDefinition.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Definitions/ConnectionPackageDefinition.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/ConnectionService.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/Contracts/IConnectionService.cs
- Added ConnectionPackage extended query
- Removed usage of IConnectionRepository in controller
- Added Delegation data to Connections
=> ConnectionPackages - Fixes

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Definitions/ConnectionDefinition.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/ConnectionService.cs
AccMgmt | Bug fix dublicate select and facilitator role null (direct delegations)
#656
- #656
=> AccMgmt | Bug fix dublicate select and facilitator role null (direct delegations)

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Internal/Controllers/AssignmentController.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Internal/Controllers/ConnectionController.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/Controllers/SystemUserClientDelegationController.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.FFB/Components/Pages/Connection_Details.razor, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Definitions/ConnectionDefinition.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Definitions/ConnectionPackageDefinition.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Repositories/ConnectionPackageRepository.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Repositories/Contracts/IConnectionPackageRepository.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/ConnectionService.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/DelegationService.cs
Changed ConnectionPackage from Cross to Extended repo.
=> ConnectionPackage - Extended

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/AssignmentService.cs, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/POST_Enduser_Connections_AddOrg.bru
Remove throw NotImplementedException
- #690
=> AccMgmt | Bugfix | Remove throw NotImplementedException

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.FFB/Components/Pages/EntityType_Index.razor, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.FFB/Components/Pages/EntityVariant_Details.razor, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.FFB/Components/Pages/Entity_Details.razor, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.FFB/Components/Pages/Package_Details.razor, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.FFB/Components/Pages/Package_Index.razor, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.FFB/Components/Pages/Provider_Index.razor, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.FFB/Components/Pages/Role_Index.razor, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Contracts/IDbBasicRepository.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Contracts/IDbCrossRepository.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Contracts/IDbExecutor.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Contracts/IDbExtendedRepository.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Executors/MssqlDbExecutor.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Executors/PostgresDbExecutor.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Models/QueryPageInfo.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Models/QueryResponse.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/QueryBuilders/PostgresQueryBuilder.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Services/BasicRepository.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Services/CrossRepository.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Services/ExtendedRepository.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Utilities/DbConverter.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Utilities/IDbConverter.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Definitions/ConnectionPackageDefinition.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/ConnectionService.cs
Changed query builder to add correct columns for pageinfo. Changed response from repository services to return pageinformation when data is paged.
=> Feature - Paging from Db

src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Manual Test Collection/Enduser/Connections/DEL_Enduser_Connections.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Manual Test Collection/Enduser/Connections/DEL_Enduser_Connections_AccPackages.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Manual Test Collection/Enduser/Connections/GET_Enduser_Connections_AccPackages.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Manual Test Collection/Enduser/Connections/GET_Enduser_Connections_FromOthers.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Manual Test Collection/Enduser/Connections/GET_Enduser_Connections_ToOthers.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Manual Test Collection/Enduser/Connections/POST_Enduser_Connections.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Manual Test Collection/Enduser/Connections/POST_Enduser_Connections_AccPackages.bru
Added Bruno Enduser Connections API manual request templates
=> AccMgmt | Bruno Enduser Connections API manual request templates

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Definitions/ConnectionDefinition.cs
Updated query to include delegation columns.
- #689
=> Bugfix | Delegation - Delegation null in response

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Metadata/Controllers/RolesController.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Helpers/FilterComparer.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/QueryBuilders/PostgresQueryBuilder.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/Contracts/IRoleService.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/Models/RoleDto.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/Models/RolePackageDto.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/RoleService.cs
La til RoleController med GetAll, GetId, Lookup (key/value) og packages for roles. 
- #502
=> Role Api i Metadata

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Internal/Controllers/AssignmentController.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Internal/Controllers/DelegationController.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Contracts/IDbCrossRepository.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/ConnectionService.cs
Removed usage of unimplemented features, CreateCross and DeleteCross,
- #699
=> Removed usage of CreateCross and DeleteCross

src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/DEL_Enduser_Conn_AccPcks_FromOthers_FromOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/DEL_Enduser_Conn_FromOthers_RemoveOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/GET_Enduser_Conn_AccPcks_FromOthers_FromOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/GET_Enduser_Conn_AccPcks_FromOthers_FromOrg_Empty.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/GET_Enduser_Conn_AccPcks_FromOthers_GetAll.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/GET_Enduser_Conn_FromOthers_GetAll.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/GET_Enduser_Conn_FromOthers_GetOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/GET_Enduser_Conn_FromOthers_GetOrg_Empty.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/POST_Enduser_Conn_AccPcks_FromOthers_ToOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/POST_Enduser_Conn_FromOthers_AddOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/DEL_Enduser_Conn_AccPcks_ToOthers_ToOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/DEL_Enduser_Conn_ToOthers_RemoveOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_AccPcks_ToOthers_GetAll.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_AccPcks_ToOthers_ToOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_AccPcks_ToOthers_ToOrg_Empty.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_ToOthers_GetAll.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_ToOthers_GetOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_ToOthers_GetOrg_Empty.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/POST_Enduser_Conn_AccPcks_ToOthers_ToOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/POST_Enduser_Conn_ToOthers_AddOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Testdata/systemuser-clientdelegation/at22.json, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Testdata/systemuser-clientdelegation/tt02.json, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/environments/YT01.bru
AccMgmt | Enduser Connections API Bruno happy-path tests
- #574
=> AccMgmt | Enduser Connections API Bruno happy-path tests

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Enduser/Services/ConnectionService.cs
=> fix: set filter that works

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Enduser/Services/ConnectionService.cs
=> fix: check the right collection

src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/DEL_Enduser_Conn_AccPcks_FromOthers_FromOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/DEL_Enduser_Conn_FromOthers_RemoveOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/GET_Enduser_Conn_AccPcks_FromOthers_FromOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/GET_Enduser_Conn_AccPcks_FromOthers_FromOrg_Empty.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/GET_Enduser_Conn_AccPcks_FromOthers_GetAll.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/GET_Enduser_Conn_FromOthers_GetAll.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/GET_Enduser_Conn_FromOthers_GetOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/GET_Enduser_Conn_FromOthers_GetOrg_Empty.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/POST_Enduser_Conn_AccPcks_FromOthers_ToOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/POST_Enduser_Conn_FromOthers_AddOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/DEL_Enduser_Conn_AccPcks_ToOthers_ToOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/DEL_Enduser_Conn_ToOthers_RemoveOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_AccPcks_ToOthers_GetAll.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_AccPcks_ToOthers_ToOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_AccPcks_ToOthers_ToOrg_Empty.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_ToOthers_GetAll.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_ToOthers_GetOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_ToOthers_GetOrg_Empty.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/POST_Enduser_Conn_AccPcks_ToOthers_ToOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/POST_Enduser_Conn_ToOthers_AddOrg.bru
- Fixed assertions for paginated response model changes
- Fixed assertions for empty array vs empty body
- Fixed assertions for non-empty array
- #574
=> AccMgmt | Bruno | Connections API test fixes

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Enduser/Controllers/ConnectionsController.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/AccessManagementHost.cs
=> fix: rename ConnectionController to ConnectionsController

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/Controllers/PolicyInformationPointController.cs
=> fix: pip access pkgs

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/Controllers/PolicyInformationPointController.cs
=> fix pip access pkgs

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/Controllers/PolicyInformationPointController.cs
Add NotSet Filter for ConnectionPackages in PIP
- #732
=> fix: add additional NotSet for ConnectionPackage

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Enduser/Controllers/ConnectionsController.cs, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/DEL_Enduser_Conn_AccPcks_FromOthers_FromOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/GET_Enduser_Conn_AccPcks_FromOthers_FromOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/GET_Enduser_Conn_AccPcks_FromOthers_FromOrg_Empty.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/GET_Enduser_Conn_AccPcks_FromOthers_GetAll.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/GET_Enduser_Conn_FromOthers_GetAll.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/GET_Enduser_Conn_FromOthers_GetOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/GET_Enduser_Conn_FromOthers_GetOrg_Empty.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/POST_Enduser_Conn_AccPcks_FromOthers_ToOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/DEL_Enduser_Conn_AccPcks_ToOthers_ToOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_AccPcks_ToOthers_GetAll.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_AccPcks_ToOthers_ToOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_AccPcks_ToOthers_ToOrg_Empty.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_ToOthers_GetAll.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_ToOthers_GetOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_ToOthers_GetOrg_Empty.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/POST_Enduser_Conn_AccPcks_ToOthers_ToOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Manual Test Collection/Enduser/Connections/Prep_SystemUserClientDelegation/POST_Enduser_Conn_AccPcks_ToOthers_ForClientDelg.bru
=> AccMgmt | POST AccessPackage rename packageUrn param and fix Bruno tests

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Data/DbDataMigrationService.cs
Endret entityvariantid fra BBL til BRLi forretningsforer-eiendom rollepakken
- #707
=> Endret entityvariantid fra BBL til BRLi forretningsforer-eiendom rollepakken

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/AccessManagementHost.cs
=> fix otel exporter to application insights

src/Directory.Packages.props, src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/AccessManagementHost.cs
=> disable application insights from service defaults

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Enduser/Controllers/ConnectionsController.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Enduser/Services/ConnectionService.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Contracts/IDbBasicRepository.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Contracts/IDbExtendedRepository.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Executors/PostgresDbExecutor.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Services/BasicRepository.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Services/ExtendedRepository.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Data/DbDataMigrationService.cs, src/libs/Altinn.Authorization.Host/src/Altinn.Authorization.Host.Database/Extensions/DbCommandExtensions.cs
=> fix: add span name to basic repository

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Enduser/Controllers/ConnectionsController.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Enduser/EnduserValidationRules.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Enduser/Services/ConnectionService.cs
=> fix validation for packages

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Core/Models/ClientDto.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/AssignmentService.cs, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Manual Test Collection/SystemUserClientDelegation/Prep_Authz_PDP_Tests/GET_SysUser_ClientDelg_GetForretningsforerClients.bru
=> AccMgmt | Get Clients | Adding UnitType check on RolePackage access for Clients

src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/SystemUserClientDelegation/GET_SysUser_BRL_ClientDelg_FFØR_AccPkg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/SystemUserClientDelegation/GET_SysUser_ClientDelg_AccPkg_Regn_org.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/SystemUserClientDelegation/NegativeTests/POST_SysUser_ClientDele_FFØR_AccPkg_ikke_BRL_Clientorg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/SystemUserClientDelegation/POST_SysUser_ClientDele_FFØR_AccPkg_BRL_Clientorg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Testdata/systemuser-clientdelegation/at22.json, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Testdata/systemuser-clientdelegation/tt02.json
Har byttet testdata for brl type client org i at22 og tt02
=> Byttet testdata med brl type client org for FFØR i at22 og tt02

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Contracts/IDbBasicRepository.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/QueryBuilders/IDbQueryBuilder.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/QueryBuilders/MssqlQueryBuilder.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/QueryBuilders/PostgresQueryBuilder.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Services/BasicRepository.cs
Fixed buggy upsert code and new method for use.
`await repository.Upsert(item, updateProperties: [t => t.Description, t => t.TypeId], compareProperties: [t => t.Name], options: options, cancellationToken: cancellationToken);`
=> Rewrite for Upsert

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/Controllers/PolicyInformationPointController.cs
=> AccMgmt | PIP API AccessPackages | Switch to use new RelationService for package lookup

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Models/Role.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/RelationService.cs
=> fix: empty deref null package

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/RelationService.cs
=> fix null ref for package

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/Controllers/PolicyInformationPointController.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/HostedServices/Services/PartySyncService.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Models/Entity.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Models/EntityLookup.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Models/Package.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Models/Role.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Definitions/DbDefinition.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Definitions/DbDefinitionBuilder.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/QueryBuilders/PostgresQueryBuilder.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Services/DbSchemaMigrationService.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Definitions/EntityLookupDefinition.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/AuthorizedPartyRepoService.cs
- La til AreaId på CompactPackage
- Fjernet RefId fra CompactEntity
- La til IsProtected på EntityLookup
- Endret CompactRole.Value => Code
- Endret CompactPackage.Value => Urn
- Fix for duplikat etter KevValue på Entity
=> Minor fixes in model for frontend

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Definitions/EntityLookupDefinition.cs
- Fixed PostScript to include correct audit information
- Added loop
=> Bug entitylookup postscript

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Enduser/Services/ConnectionService.cs
=> Allow automatic rettighetshaver assignment based on an existing relation

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence.Core/Services/DbSchemaMigrationService.cs
- Added placeholder function for dependent function.
=> Bug fix - Migration functions

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/HostedServices/Services/PartySyncService.cs, src/libs/Altinn.Authorization.Integration/src/Altinn.Authorization.Integration.Platform/AccessManagement/AltinnAccessManagementClient.cs, src/libs/Altinn.Authorization.Integration/src/Altinn.Authorization.Integration.Platform/AccessManagement/AltinnAccessManagementOptions.cs, src/libs/Altinn.Authorization.Integration/src/Altinn.Authorization.Integration.Platform/Appsettings/PlatformSettings.cs, src/libs/Altinn.Authorization.Integration/src/Altinn.Authorization.Integration.Platform/Extensions/ServiceCollectionExtensions.cs, src/libs/Altinn.Authorization.Integration/src/Altinn.Authorization.Integration.Platform/PlatformResponse.cs, src/libs/Altinn.Authorization.Integration/src/Altinn.Authorization.Integration.Platform/Register/AltinnRegisterClient.cs, src/libs/Altinn.Authorization.Integration/src/Altinn.Authorization.Integration.Platform/Register/PartiesStreamEndpoint.cs, src/libs/Altinn.Authorization.Integration/src/Altinn.Authorization.Integration.Platform/Register/RoleStreamEndpoint.cs, src/libs/Altinn.Authorization.Integration/src/Altinn.Authorization.Integration.Platform/ResourceRegister/AltinnResourceRegisterClient.cs, src/libs/Altinn.Authorization.Integration/src/Altinn.Authorization.Integration.Platform/ResourceRegister/ResourceGetEndpoint.cs, src/libs/Altinn.Authorization.Integration/src/Altinn.Authorization.Integration.Platform/ResourceRegister/ResourceUpdatedEndpoint.cs, src/libs/Altinn.Authorization.Integration/src/Altinn.Authorization.Integration.Platform/ResourceRegister/ServiceOwnersEndpoints.cs, src/libs/Altinn.Authorization.Integration/src/Altinn.Authorization.Integration.Platform/SblBridge/AltinnSblBridgeClient.cs, src/libs/Altinn.Authorization.Integration/src/Altinn.Authorization.Integration.Platform/SblBridge/AltinnSblBridgeOptions.cs, src/libs/Altinn.Authorization.Integration/test/Altinn.Authorization.Integration.Tests/Register/PartiesStreamEndpointTest.cs
=> Bootstrap SBL bridge in lib platform

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Definitions/RelationPermissionDefinition.cs, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/DEL_Enduser_Conn_ToOthers_RemoveOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_AccPcks_ToOthers_ToDagl.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_AccPcks_ToOthers_ToOrg_Empty.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_ToOthers_GetAll.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_ToOthers_GetOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_ToOthers_GetOrg_Empty.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/POST_Enduser_Conn_AccPcks_ToOthers_To_type_Org.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/POST_Enduser_Conn_ToOthers_Add_different_types_Org.bru
- Added RolePackages to RelationPermission
- #860
=> Bug - ER Role packages

infra/deploy/spoke/service_bus.tf, infra/modules/application_gateway/main.tf, infra/modules/key_vault/main.tf
=> chores: update azure diagnostics

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Metadata/Controllers/PackagesController.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/Contracts/IPackageService.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/PackageService.cs
- Added option to searchInResources. 
- Removed search in Resource.Description
=> Bug - MetaData Api - Slow search on resources

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Integration/Clients/ResourceRegistryClient.cs
Added caching for consent templates
=> Added caching

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/HostedServices/Services/PartySyncService.cs, src/libs/Altinn.Authorization.Integration/src/Altinn.Authorization.Integration.Platform/Register/PartiesStreamEndpoint.cs
=> issues (773): add userid

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/AMPartyService.cs
=> AccMgmt | Fix entity lookup service to not use "like" in query

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Enduser/EnduserValidationRules.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Enduser/Services/ConnectionService.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Models/EntityType.cs, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/DEL_Enduser_Conn_AccPcks_ToOthers_ToOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/DEL_Enduser_Conn_Active_delegert_Rightholder_with_cascade.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/DEL_Enduser_Conn_ToOthers_RemoveOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_AccPkg_KundeLista.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_AccPkg_KundeLista_After_deleting_rightholders.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_AccPcks_ToOthers_GetAll.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_AccPcks_ToOthers_ToDagl.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_AccPcks_ToOthers_ToOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_AccPcks_ToOthers_ToOrg_Empty.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_AccPkg_After_Delet_AccPkg_delegation.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_AccPkg_To_different_types_org.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_Rightholder_To_different_types_org.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_ToOthers_GetAll.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_ToOthers_GetOrg_Empty.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/POST_Enduser_Conn_AccPcks_ToOthers_To_type_Org.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/POST_Enduser_Conn_HADM_AccPcks_Delegation.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/POST_Enduser_Conn_MainAdmin_ToOthers_ToOrg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/POST_Enduser_Conn_ToOthers_Add_Org_with_HADM.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/POST_Enduser_Conn_ToOthers_Add_different_types_Org.bru
=> AccMgmt | Make hovedadministrator package not assignable to organizations

infra/modules/postgres/main.tf, infra/modules/postgres/variables.tf
=> chores: add default pgbouncer configuration to TF

src/apps/Altinn.Register/infra/at22.tfvars, src/apps/Altinn.Register/infra/main.tf, src/apps/Altinn.Register/infra/variables.tf, src/tools/Altinn.Authorization.Cli/src/Altinn.Authorization.Cli/Database/BootstapCommand.cs
=> chores: add use-pgbouncer flag to cli tool

src/apps/Altinn.Register/infra/variables.tf
=> chores: update storage tier that's compatible with storage_mb

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Enduser/EnduserValidationRules.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Enduser/Services/EnduserConnectionService.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Core/Errors/ValidationErrors.cs
Add delegation check for package assignment in enduser API
- #1029
=> issues(1029):  user delegation check in package assignment

src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/POST_Enduser_Conn_FromOthers_Add_different_type_org.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/GET_Enduser_Conn_AccPkg_To_different_types_org.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/Negative_scenarioer/folder.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/POST_Enduser_Conn_ToOthers_Add_different_types_Org.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/SystemUserClientDelegation/GET_SysUser_BRL_ClientDelg_FFØR_AccPkg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/SystemUserClientDelegation/GET_SysUser_ClientDelg_AccPkg_Regn_org.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/SystemUserClientDelegation/GET_SysUser_ESEK_ClientDelg_FFØR_AccPkg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/SystemUserClientDelegation/GET_SystemUser_EnkClientDelegations.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/Virksomhetsdelegering/GET_AccPkg_KundeLista_med_Både_pakker.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/Virksomhetsdelegering/POST_SysUser_ClientDele_AccPkg_Vanlig_pakke_Delegering_HADM.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Testdata/enduser/at22.json, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Testdata/enduser/tt02.json, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Testdata/systemuser-clientdelegation/at22.json, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Testdata/systemuser-clientdelegation/tt02.json
=> Made changes to fix failing system-integration tests in AT22 and TT02

src/apps/Altinn.Authorization/src/Altinn.Authorization/Controllers/DecisionController.cs
- Changed json deserialization to to be case insensitive
- #{issue number}
=> Changed json deserialization to to be case insensitive

src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Manual Test Collection/InternalAPI/Connections/DELETE_Internal_Conn_AccPcks_RmvSysUsr.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Manual Test Collection/InternalAPI/Connections/DELETE_Internal_Conn_RmvSysUsr.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Manual Test Collection/InternalAPI/Connections/GET_Internal_Conn_AccPcks_GetAll.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Manual Test Collection/InternalAPI/Connections/GET_Internal_Conn_GetAll.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Manual Test Collection/InternalAPI/Connections/POST_Enduser_Conn_AccPcks_ToSysUsr.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Manual Test Collection/InternalAPI/Connections/POST_Internal_Conn_AddSysUsr.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Manual Test Collection/InternalAPI/Party/POST_Internal_Party_SystemUser.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Testdata/manualtests/systemuser-directdelegation/at22.json, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Testdata/manualtests/systemuser-directdelegation/tt02.json
- Manual request templates added for Internal Connections and Party
=> AccMgmt | Bruno | Manual request templates added for Internal Connections and Party

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Internal/Controllers/PartyController.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Data/DbDataMigrationService.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/DelegationService.cs, src/apps/Altinn.AccessManagement/test/AccessMgmt.Tests/Controllers/PartyControllerTests.cs, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/InternalAPI/Party/POST_Internal_Party_InvalidAppClaim.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/InternalAPI/Party/POST_Internal_Party_InvalidIssuer.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/InternalAPI/Party/POST_Internal_Party_UuidExists.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Manual Test Collection/InternalAPI/Party/POST_Internal_Party_SystemUser.bru
- Added new AgentSystem and StandardSystem entity variants for systemusers
- Changed to 201 Created response when party created successfully
- Updated tests
- #1039
=> AccMgmt | Updates to POST internal/party

src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/DEL_Enduser_Conn_Active_delegert_Avgiver_with_cascade.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/GET_Enduser_Conn_AccPcks_After_deleting_AccPkg_FromOrg_empty.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/POST_Enduser_Conn_HADM_AccPcks_Delegation.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/Virksomhetsdelegering/GET_AccPkg_KundeLista_med_Både_pakker.bru
=> Fixed system-integration failing tests

src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/GET_Enduser_Conn_AccPcks_From_other_org.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/POST_Enduser_Conn_AccPcks_Delegation_Different_type_org.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/Negative_scenarioer/POST_Enduser_Conn_AccPcks_Delegate_HADM_AccPkg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/SystemUserClientDelegation/GET_SysUser_BRL_ClientDelg_FFØR_AccPkg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/SystemUserClientDelegation/POST_SysUser_ClientDele_FFØR_AccPkg_BRL_Clientorg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/SystemUserClientDelegation/POST_SysUser_ClientDele_FFØR_AccPkg_ESEK_Clientorg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/meta/roles/GET_roles_lookup.bru
=> AccMgmt | Fix broken automated bruno tests

src/libs/Altinn.Authorization.Host/src/Altinn.Authorization.Host.Lease/StorageAccount/StorageAccountLease.cs
=> chores: increase lease skew

src/apps/Altinn.Register/infra/main.tf, src/apps/Altinn.Register/infra/tt02.tfvars
=> chores: tf format

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/HostedServices/Services/PartySyncService.cs
=> chores: if user is something and not 0

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/AccessManagementHost.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.PersistenceEF/Extensions/ServiceCollectionExtensions.cs
=> chores: add EF service collection stuffy

src/libs/Altinn.Authorization.Host/src/Altinn.Authorization.Host.Lease/StorageAccount/StorageAccountLease.cs, src/libs/Altinn.Authorization.Host/src/Altinn.Authorization.Host.Lease/Telemetry/LeaseTelemetry.cs, src/libs/Altinn.Authorization.Host/test/Altinn.Authorization.Host.Lease.Tests/StorageAccount/StorageAccountLeaseTest.cs
=> chores: ensure that DisposeAsync is properly called

.github/scripts/package.json, .github/scripts/pnpm-lock.yaml
(https://github.com/Altinn/altinn-authorization-tmp/security/dependabot/9)
Update all dependencies on undici 
- #1153
=> Resolve dependabot alert #9

.github/workflows/_deploy-app.yml, .github/workflows/cd-apps.yml, .github/workflows/ci.yml, .github/workflows/mirror-images.yml, .github/workflows/tpl-find-verticals.yml, .github/workflows/tpl-vertical-ci.yml
=> Added permission blocks in the workflows that trigger codeql alerts

.github/workflows/run-scheduled-authorized-parties.yml
Set new time for scheduled test to check if it works
- #{issue number}
=> setting new time for scheduled test run

infra/deploy/hub/.terraform.lock.hcl, infra/deploy/hub/main.tf, infra/deploy/spoke/.terraform.lock.hcl, infra/deploy/spoke/main.tf, infra/modules/postgres/variables.tf, src/apps/Altinn.AccessManagement/infra/.terraform.lock.hcl, src/apps/Altinn.AccessManagement/infra/main.tf, src/apps/Altinn.Authorization/infra/.terraform.lock.hcl, src/apps/Altinn.Authorization/infra/main.tf, src/apps/Altinn.Register/infra/.terraform.lock.hcl, src/apps/Altinn.Register/infra/main.tf
* Patch Azurerm provider
* Upgrade all pgsql flex server from 16 -> 17
- #1305
=> issues(1305):  upgrade pgsql flex from 16 to 17 and patch azurerm module

infra/modules/key_vault/main.tf, src/apps/Altinn.AccessManagement/infra/main.tf
=> chores: format accessmgmt and fix deprecated kv field

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Metadata/Altinn.AccessManagement.Api.Metadata.csproj, src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Metadata/Controllers/PackagesController.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Metadata/Controllers/RolesController.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Services/Contracts/IPackageService.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Services/Contracts/IRoleService.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Services/DelegationService.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Services/PackageService.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Utils/Mappers/DtoMapper.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Utils/Mappers/DtoMapperPermissionDto.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Persistence/Services/RelationService.cs
Converted MetaDataAPI to use EF
- #1322
=> Converted MetaDataApi to use EF

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/AccessManagementHost.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Services/PackageService.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Services/RoleService.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Utils/Mappers/DtoMapperRolePackage.cs
- Fix for EF Services missing
- Added includes
- Removed SearchCache
- Minor fixes in converter
- #1322
- #1323
=> Bugfix for Metadata API

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Internal/Controllers/PartyController.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Extensions/ServiceCollectionExtensions.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Services/Contracts/IPartyService.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Services/PartyService.cs, src/libs/Altinn.Authorization.Api.Contracts/src/Altinn.Authorization.Api.Contracts/Party/PartyBaseDto.cs
Refactored PartyService.AddParty parameters.
Refactored PartyController.AddParty.
Added validation attributes to PartyBaseDto model.
Corrected AuditValues setup for PartyService.
Much change, very code.
- #1334
=> Refaktorering av Internal API for EF - PartyController

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Services/ConnectionService.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.PersistenceEF/Extensions/ServiceCollectionExtensions.cs
=> chores: follow MS docs 

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Enduser/Controllers/ConnectionsController.cs
=> chores: fix response model access pkg

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Services/ConnectionService.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.PersistenceEF/Extensions/IQueryableExtensions.cs
=> chores: include full entity

src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/FromOthers/GET_Enduser_Conn_RightHolder_From_other_org.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/Negative_scenarioer/POST_Enduser_Conn_ToOthers_Add_different_types_Org_Negative.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/EnduserAPI/Connections/ToOthers/POST_Enduser_Conn_ToOthers_Add_Org_with_HADM.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/SystemUserClientDelegation/DEL_SysUser_ClientDelg_AccPkgForDelete_AgentAssignmentid_false.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/SystemUserClientDelegation/NegativeTests/DEL_SysUser_BRL_ClientDelg_AccPkgForDelete_agentid_false.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/SystemUserClientDelegation/NegativeTests/DEL_SysUser_ClientDelg_AccPkgForDelete_agentid_false.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/SystemUserClientDelegation/NegativeTests/POST_SysUser_ClientDele_AccPkg_invalid_package.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/SystemUserClientDelegation/NegativeTests/POST_SysUser_ClientDele_AccPkg_to_person_negative.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/SystemUserClientDelegation/NegativeTests/POST_SysUser_ClientDele_FFØR_AccPkg_ikke_BRL_Clientorg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/SystemUserClientDelegation/NegativeTests/POST_SysUser_ClientDelg_AccPkg_without_ClientDeleg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/Virksomhetsdelegering/DEL_SysUser_ClientDelg_Vanlig_AccPkgForDelete_agentid_false.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/Virksomhetsdelegering/GET_AccPkg_KundeLista_med_Både_pakker.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/meta/accesspackage/GET_accesspackage_group_bransje_areas.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/meta/accesspackage/GET_accesspackage_packages_for_kultur_og_frivillighet.bru
Fikset 3 flaky brunotester og endret 7 så de forvente 400 response i stedet for 500.
- #1380
=> Chore: Fikset brunotester

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Services/ConnectionService.cs
- Fixed service to only remove package not the assignment
- #1411
=> Bug - Remove AssignmentPackage

src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/SystemUserClientDelegation/NegativeTests/DEL_SysUser_ClientDelg_AccPkgForDelete_agentid_false.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/SystemUserClientDelegation/NegativeTests/POST_SysUser_ClientDele_AccPkg_invalid_package.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/SystemUserClientDelegation/NegativeTests/POST_SysUser_ClientDele_AccPkg_to_person_negative.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/SystemUserClientDelegation/NegativeTests/POST_SysUser_ClientDele_FFØR_AccPkg_ikke_BRL_Clientorg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/SystemUserClientDelegation/NegativeTests/POST_SysUser_ClientDelg_AccPkg_without_ClientDeleg.bru, src/apps/Altinn.AccessManagement/test/Bruno/AccessMgmt/Automatic Test Collection/Virksomhetsdelegering/Internal/Negative/DELETE_Internal_Conn_Delete_SystemUser_Cannot_Delete_Without_Cascade_Negative_Test.bru
Endret noen brunotester til å forvente 500 response i stedet for 400, rettet på noen andre brunotester.
- #{issue number}
=> Brunotest fixes

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Services/DelegationService.cs
- The check on name only makes headaches for testing
- Also names might be possible to change in the future, and our receipt of these changes through Register might not be in-time for new delegations
- Check is missing validation that the system user is of variant AgentSystem
- #1422 1422
=> bug: better validation check for existing agent systemuser

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Utils/Mappers/DtoMapper.cs
- Added CalculateDateOfBirth to DtoMapper
- #1423
=> Bug | AccMgmt - Fix DateOfBirth in DtoMapper

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.PersistenceEF/Extensions/AuditValues.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.PersistenceEF/Extensions/ServiceCollectionExtensions.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.PersistenceEF/Queries/PackageDelegationCheckQuery.cs
- Removed DbContextPooling
- Possible to switch with options
- #1427
=> Removed DbContextPooling

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Services/ConnectionService.cs
=> chores: fix read validation

src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Services/ConnectionService.cs
=> chores: fix if statement stuffy

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement/AccessManagementHost.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.PersistenceEF/Extensions/ServiceCollectionExtensions.cs
- Added correct connectionstrings
- Included Factory CreateDbContext for Audit
- #1427
=> AccMgmt - Bug - Correct ConnectionStrings and Audit in Factory

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Enduser/Controllers/ConnectionsController.cs
=> bug: Toggle DelegationCheck back on (debugging complete)

src/apps/Altinn.AccessManagement/src/Altinn.AccessManagement.Api.Enduser/Controllers/ConnectionsController.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Services/ConnectionService.cs, src/apps/Altinn.AccessManagement/src/Altinn.AccessMgmt.Core/Validation/EntityTypeValidation.cs
=> fix allowed entity types
